### ISSUE TITLE
Not related to this at all but this is the only real way I could contact you (see comment)

### ISSUE THREAD

**Issue by ghost** [Atvaark/dragons-dogma-server#1]
Over the past few hours I've been desperately looking for a way to deal with NieR Automata's sound files and apparently you made something that helps deal with them? There was a gist you made but it looks like you've deleted it but the original URL was "https://gist.githubusercontent.com/Atvaark/680d189c0f35acc0f1eb4a14519eba6a/raw/eb1ba9a20d5b140a96ba0e48cbee21d258416632/nier-sound-extractor.zip" if that helps. 
I hope you can get back to me, thanks
It's totally fine if not

**Comment by Atvaark** [comment]
Hey,

I can reupload the tool and its source code if you want.
[nier-sound-extractor.zip](https://github.com/Atvaark/dragons-dogma-server/files/3941087/nier-sound-extractor.zip)

See here for instructions: https://steamcommunity.com/groups/nierMnM/discussions/2/135512625246228407/#c1319962329028977650
